---
version: '3'

services:

  mainservice:
    build: .
    ports:
      - 3003:3000
      - 9229:9229
      - 5555:5555
    volumes:
      - .:/home/node/app
    depends_on:
      mainservicedb:
        condition: service_healthy
    networks:
      myservices:

  mainservicedb:
    image: postgres
    volumes:
      - ./.docker/pgdbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mainservice
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      myservices:

networks:
  myservices:
    driver: bridge
