FROM node:latest

WORKDIR /home/node/app

RUN apt update
RUN apt install git

COPY . .

RUN npm install
RUN npm run build

# Comando para iniciar a aplicação
CMD ["node", "/home/node/app/dist/src/main.js"]
