# .github/workflows/build-and-update-manifest.yaml
name: Build and Update Manifest

on:
  push:
    branches:
      - main  # Execute ao fazer push na branch principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use Google Cloud Registry
        run: |
          gcloud auth configure-docker

      - name: Start Cloud SQL Proxy
        id: start-sql-proxy
        run: |
          curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
          chmod +x cloud_sql_proxy
          ./cloud_sql_proxy -instances=dev-default-382019:us-east4:diel-database-instance=tcp:3306 &
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a versão desejada do Node.js

      - name: Install Dependencies
        run: npm install

      - name: Install expect
        run: |
          sudo apt-get update
          sudo apt-get install -y expect

      - name: Run Prisma Migrate Dev
        env:
          DATABASE_URL: "mysql://develbackend:5hC589lGm1oK@127.0.0.1:3306/mainservice" # Substitua com sua string de conexão
        run: |
          ./devops/prisma-migrate-dev.expect

      - name: Stop Cloud SQL Proxy
        run: |
          pkill cloud_sql_proxy

      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: "v${{ github.run_number }}"  # Define a tag única para cada build
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          cp .env_example .env
          docker build -t gcr.io/$GCP_PROJECT_ID/main-service-teste:${IMAGE_TAG} -f Dockerfile.kube .
          docker push gcr.io/$GCP_PROJECT_ID/main-service-teste:${IMAGE_TAG}
          docker image rm  gcr.io/$GCP_PROJECT_ID/main-service-teste:${IMAGE_TAG}

      - name: Checkout Manifest Repository
        uses: actions/checkout@v2
        with: 
          repository: dielenergia/manifests-kubernetes # Nome do repositório de manifestos
          token: ${{ secrets.GIT_TOKEN }}
          path: manifest-repo

      - name: List Manifest Repository Files
        run: ls -R manifest-repo

      - name: Check Git Status
        working-directory: manifest-repo
        run: git status

      - name: Update Deployment Manifest
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE_TAG: "v${{ github.run_number }}"
        run: |
          sed -i "s|image: gcr.io/.*/main-service.*|image: gcr.io/$GCP_PROJECT_ID/main-service-teste:${IMAGE_TAG}|g" manifest-repo/main-service/deploy.yaml

      - name: Commit and Push Manifest Update
        working-directory: manifest-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Atualiza a imagem para a versão $IMAGE_TAG"
          git push
